spring:
  application:
    name: springflix-trailers
  cloud:
    refresh:
      enabled: false

app:
  client:
    connectTimeout: 30s
    readTimeout: 30s
  tmdb:
    api:
      url: https://api.themoviedb.org
      key:

server:
  port: ${PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: "*"
