spring:
  application:
    name: springflix-trailers

app:
  client:
    connectTimeout: 30s
    readTimeout: 30s
  tmdb:
    api:
      url: https://api.themoviedb.org
      key:

server:
  port: ${PORT:8083}

springdoc:
  api-docs:
    path: /api/openapi

management:
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    metrics:
      export:
        enabled: false

---

spring:
  config:
    activate:
      on-cloud-platform: kubernetes

management:
  otlp:
    metrics:
      export:
        enabled: true
